<a href="https://colab.research.google.com/github/poudel-bibek/Intro-to-AI-Assignments/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## A new notebook for basics
- First things sirst
- Second things second

__First__: Getting to know Numpy.

In [2]:
import numpy as np

In [3]:
# list
a = [0,1,2,3,4,5]

In [4]:
# np array from list
np.array(a)

array([0, 1, 2, 3, 4, 5])

In [7]:
# np array directly
b = np.array([1,2,3,4,5,6])

In [8]:
# dimensions of an array (vector)
b.shape

(6,)

In [9]:
# reshape to a 3 x 2 matrix
c = b.reshape(3,2)

In [10]:
# dimensions of matrix
c.shape

(3, 2)

In [27]:
# one more array
d = np.array([5,6,7,8,9,10])

# Add 2 numpy arrays directly
e = b + d

e

array([ 6,  8, 10, 12, 14, 16])

In [26]:
# Multiply 2 numpy arrays
f = b*d
print(f)
print(f.shape)

[ 5 12 21 32 45 60]
(6,)


In [25]:
# Every element of the array raised to power of 2
g = b**2
g

array([ 1,  4,  9, 16, 25, 36])

In [17]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# Array of ones
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# Statistics from an array

# mean
print(np.mean(b))

# standard deviation
print(np.std(b))

# variance
print(np.var(b))

3.5

In [20]:
# minimum
print(np.min(b))

# maximum
print(np.max(b))

1.707825127659933